export const ErrorCodes = {
    //user general errors
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ID_NOT_FOUND: 'USER_ID_NOT_FOUND',
    USER_NOT_CREATED: 'USER_NOT_CREATED',
    USER_NOT_UPDATED: 'USER_NOT_UPDATED',
    USER_ID_NOT_UPDATED: 'USER_ID_NOT_UPDATED',

    PROFILE_ID_INVALID: 'PROFILE_ID_INVALID',
    ROLE_ID_REQUIRED: 'ROLE_ID_REQUIRED',
    CLERK_ID_REQUIRED: 'CLERK_ID_REQUIRED',
    USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
    USER_PHONE_EXISTS: 'USER_PHONE_EXISTS',

    

    //employer errors
    EMPLOYER_NOT_FOUND: 'EMPLOYER_NOT_FOUND',
    EMPLOYER_ID_NOT_FOUND: 'EMPLOYER_ID_NOT_FOUND',
    EMPLOYER_NOT_CREATED: 'EMPLOYER_NOT_CREATED',
    EMPLOYER_NOT_UPDATED: 'EMPLOYER_NOT_UPDATED',
    EMPLOYER_ID_NOT_UPDATED: 'EMPLOYER_ID_NOT_UPDATED',
    EMPLOYER_NOT_DELETED: 'EMPLOYER_NOT_DELETED',
    EMPLOYER_ID_NOT_DELETED: 'EMPLOYER_ID_NOT_DELETED',
    EMPLOYER_NOT_ACTIVATED: 'EMPLOYER_NOT_ACTIVATED',
    EMPLOYER_ID_NOT_ACTIVATED: 'EMPLOYER_ID_NOT_ACTIVATED',
    
    //recruiter errors
    RECRUITER_NOT_FOUND: 'RECRUITER_NOT_FOUND',
    RECRUITER_ID_NOT_FOUND: 'RECRUITER_ID_NOT_FOUND',
    RECRUITER_NOT_CREATED: 'RECRUITER_NOT_CREATED',
    RECRUITER_NOT_UPDATED: 'RECRUITER_NOT_UPDATED',
    RECRUITER_ID_NOT_UPDATED: 'RECRUITER_ID_NOT_UPDATED',

    //candidate errors
    CANDIDATE_NOT_FOUND: 'CANDIDATE_NOT_FOUND',
    CANDIDATE_ID_NOT_FOUND: 'CANDIDATE_ID_NOT_FOUND',
    CANDIDATE_NOT_CREATED: 'CANDIDATE_NOT_CREATED',
    CANDIDATE_NOT_UPDATED: 'CANDIDATE_NOT_UPDATED',
    CANDIDATE_ID_NOT_UPDATED: 'CANDIDATE_ID_NOT_UPDATED',
    CANDIDATE_NOT_ACTIVATED: 'CANDIDATE_NOT_ACTIVATED',
    CANDIDATE_ID_NOT_ACTIVATED: 'CANDIDATE_ID_NOT_ACTIVATED',

    CANDIDATE_IDEAL_JOB_NOT_UPDATED: 'CANDIDATE_IDEAL_JOB_NOT_UPDATED',
    
    //admin errors
    ADMIN_EMPLOYER_NOT_DELETED: 'ADMIN_EMPLOYER_NOT_DELETED',
    ADMIN_EMPLOYER_NOT_FOUND: 'ADMIN_EMPLOYER_NOT_FOUND',
    ADMIN_EMPLOYER_ID_NOT_FOUND: 'ADMIN_EMPLOYER_ID_NOT_FOUND',
    ADMIN_OR_COMPANY_NOT_FOUND: 'ADMIN_OR_COMPANY_NOT_FOUND',

    //company errors
    COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
    COMPANY_ID_NOT_FOUND: 'COMPANY_ID_NOT_FOUND',
    COMPANY_ID_REQUIRED: 'COMPANY_ID_REQUIRED',
    COMPANY_NOT_UPDATED: 'COMPANY_NOT_UPDATED',
    COMPANY_ID_NOT_UPDATED: 'COMPANY_ID_NOT_UPDATED',
    COMPANY_NOT_VALIDATED: 'COMPANY_NOT_VALIDATED',
    COMPANY_ID_NOT_VALIDATED: 'COMPANY_ID_NOT_VALIDATED',
    COMPANY_NAME_EXISTS: 'COMPANY_NAME_EXISTS',

    //invite errors
    INVITE_NOT_CREATED: 'INVITE_NOT_CREATED',
    INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
    INVITE_NOT_FOUND_OR_EXPIRED: 'INVITE_NOT_FOUND_OR_EXPIRED',
    INVITE_INVALID: 'INVITE_INVALID',
    INVITE_EXPIRED: 'INVITE_EXPIRED',
    INVITE_ALREADY_USED: 'INVITE_ALREADY_USED',
    INVITE_NOT_UPDATED: 'INVITE_NOT_UPDATED',

    UPDATED_INVITE_NOT_FOUND: 'UPDATED_INVITE_NOT_FOUND',
    NO_JOB_FOR_INVITE: 'NO_JOB_FOR_INVITE',
    CANDIDATE_RECRUITER_CONNECTION_FAILED: 'CANDIDATE_RECRUITER_CONNECTION_FAILED',
    INVITE_AND_APPLICATION_ALREADY_EXISTS: 'INVITE_AND_APPLICATION_ALREADY_EXISTS',

    //job errors
    JOB_NOT_FOUND: 'JOB_NOT_FOUND',
    JOB_ID_NOT_FOUND: 'JOB_ID_NOT_FOUND',
    JOB_NOT_FOUND_OR_ACCESS_DENIED: 'JOB_NOT_FOUND_OR_ACCESS_DENIED',
    JOB_NOT_UPDATED: 'JOB_NOT_UPDATED',
    JOB_ID_NOT_UPDATED: 'JOB_ID_NOT_UPDATED',
    JOB_NOT_DELETED: 'JOB_NOT_DELETED',
    JOB_ID_NOT_DELETED: 'JOB_ID_NOT_DELETED',
    JOB_WITH_APPLICATIONS_NOT_DELETED: 'JOB_WITH_APPLICATIONS_NOT_DELETED',
    JOB_WITH_CANDIDATE_APPLICATIONS_NOT_DELETED: 'JOB_WITH_CANDIDATE_APPLICATIONS_NOT_DELETED',
    JOB_WITH_CALENDAR_EVENTS_NOT_DELETED: 'JOB_WITH_CALENDAR_EVENTS_NOT_DELETED',

    //job application errors
    JOB_APPLICATION_ALREADY_EXISTS: 'JOB_APPLICATION_ALREADY_EXISTS',
    JOB_APPLICATION_NOT_FOUND: 'JOB_APPLICATION_NOT_FOUND',
    JOB_APPLICATION_ID_NOT_FOUND: 'JOB_APPLICATION_ID_NOT_FOUND',
    JOB_APPLICATION_NOT_APPROVED: 'JOB_APPLICATION_NOT_APPROVED',
    JOB_APPLICATION_ID_NOT_APPROVED: 'JOB_APPLICATION_ID_NOT_APPROVED',
    JOB_APPLICATION_NOT_REJECTED: 'JOB_APPLICATION_NOT_REJECTED',
    JOB_APPLICATION_ID_NOT_REJECTED: 'JOB_APPLICATION_ID_NOT_REJECTED',

    AUTOAPPROVAL_ON_NOT_CREATED: 'AUTOAPPROVAL_ON_NOT_CREATED',
    AUTOAPPROVAL_OFF_NOT_CREATED: 'AUTOAPPROVAL_OFF_NOT_CREATED',
    RECRUITER_NOT_APPROVED_FOR_JOB: 'RECRUITER_NOT_APPROVED_FOR_JOB',

    //candidate job application errors
    CANDIDATE_JOB_APPLICATION_ALREADY_EXISTS: 'CANDIDATE_JOB_APPLICATION_ALREADY_EXISTS',
    CANDIDATE_JOB_APPLICATION_NOT_CREATED: 'CANDIDATE_JOB_APPLICATION_NOT_CREATED',
    CANDIDATE_JOB_APPLICATION_NOT_FOUND: 'CANDIDATE_JOB_APPLICATION_NOT_FOUND',
    CANDIDATE_JOB_APPLICATION_ID_NOT_FOUND: 'CANDIDATE_JOB_APPLICATION_ID_NOT_FOUND',
    CANDIDATE_JOB_APPLICATION_NOT_UPDATED: 'CANDIDATE_JOB_APPLICATION_NOT_UPDATED',
    CANDIDATE_JOB_APPLICATION_ID_NOT_UPDATED: 'CANDIDATE_JOB_APPLICATION_ID_NOT_UPDATED',
    CANDIDATE_JOB_APPLICATION_NOT_REJECTED: 'CANDIDATE_JOB_APPLICATION_NOT_REJECTED',
    CANDIDATE_JOB_APPLICATION_ID_NOT_REJECTED: 'CANDIDATE_JOB_APPLICATION_ID_NOT_REJECTED',

    //job hire errors
    JOB_HIRES_LIMIT_REACHED: 'JOB_HIRES_LIMIT_REACHED',
    CANDIDATE_ALREADY_HIRED_FOR_ANOTHER_JOB: 'CANDIDATE_ALREADY_HIRED_FOR_ANOTHER_JOB',
    JOB_HIRE_NOT_CREATED: 'JOB_HIRE_NOT_CREATED',
    HIRE_NOT_FOUND_OR_ALREADY_TERMINATED: 'HIRE_NOT_FOUND_OR_ALREADY_TERMINATED',
    HIRE_NOT_TERMINATED: 'HIRE_NOT_TERMINATED',

    //job stage errors
    STAGE_NOT_FOUND: 'STAGE_NOT_FOUND',
    STAGE_ID_NOT_FOUND: 'STAGE_ID_NOT_FOUND',
    STAGE_NOT_CREATED: 'STAGE_NOT_CREATED',
    STAGE_NOT_UPDATED: 'STAGE_NOT_UPDATED',
    STAGE_ID_NOT_UPDATED: 'STAGE_ID_NOT_UPDATED',
    STAGE_NOT_DELETED: 'STAGE_NOT_DELETED',
    STAGE_ID_NOT_DELETED: 'STAGE_ID_NOT_DELETED',
    STAGE_ORDER_NOT_UPDATED: 'STAGE_ORDER_NOT_UPDATED',

    //event errors
    EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
    EVENT_ID_NOT_FOUND: 'EVENT_ID_NOT_FOUND',
    EVENT_NOT_CREATED: 'EVENT_NOT_CREATED',
    EVENT_NOT_UPDATED: 'EVENT_NOT_UPDATED',
    EVENT_ID_NOT_UPDATED: 'EVENT_ID_NOT_UPDATED',
    EVENT_NOT_DELETED: 'EVENT_NOT_DELETED',
    EVENT_ID_NOT_DELETED: 'EVENT_ID_NOT_DELETED',
    
    //activity log errors
    ACTIVITY_TYPE_NOT_FOUND: 'ACTIVITY_TYPE_NOT_FOUND',
    ACTIVITY_TYPE_CODE_NOT_FOUND: 'ACTIVITY_TYPE_CODE_NOT_FOUND',
    ACTIVITY_TYPE_ID_NOT_FOUND: 'ACTIVITY_TYPE_ID_NOT_FOUND',
    ACTIVITY_LOG_NOT_CREATED: 'ACTIVITY_LOG_NOT_CREATED',
    ACTIVITY_FEED_NOT_FETCHED: 'ACTIVITY_FEED_NOT_FETCHED',
    JOB_ACTIVITIES_NOT_FETCHED: 'JOB_ACTIVITIES_NOT_FETCHED',
    CANDIDATE_ACTIVITIES_NOT_FETCHED: 'CANDIDATE_ACTIVITIES_NOT_FETCHED',
    RECRUITER_ACTIVITIES_NOT_FETCHED: 'RECRUITER_ACTIVITIES_NOT_FETCHED',

    //message errors
    MESSAGE_NOT_CREATED: 'MESSAGE_NOT_CREATED',

    //review errors
    REVIEW_NOT_CREATED: 'REVIEW_NOT_CREATED',

    //todo errors
    TODO_NOT_FOUND: 'TODO_NOT_FOUND',
    TODO_ID_NOT_FOUND: 'TODO_ID_NOT_FOUND',
    TODO_NOT_CREATED: 'TODO_NOT_CREATED',
    TODO_NOT_UPDATED: 'TODO_NOT_UPDATED',
    TODO_ID_NOT_UPDATED: 'TODO_ID_NOT_UPDATED',
    TODO_NOT_DELETED: 'TODO_NOT_DELETED',
    TODO_ID_NOT_DELETED: 'TODO_ID_NOT_DELETED',
};

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];