import { NotificationTypeCode } from "../constants.js";
import { NOTIF_CATEG__GENERAL, NOTIF_CATEG__HIRING_PROCESS, PROFILE_CANDIDATE, PROFILE_EMPLOYER, PROFILE_RECRUITER, type NotificationType } from "../index.js";
import { NOTIF_GROUP__CANDIDATE_INTERVIEWS, NOTIF_GROUP__CANDIDATE_MESSAGES, NOTIF_GROUP__CANDIDATE_REVIEWS, NOTIF_GROUP__CANDIDATE_STAGE_UPDATES, NOTIF_GROUP__CANDIDATE_STATUS_UPDATES, NOTIF_GROUP__EMPLOYER_CANDIDATE_UPDATES, NOTIF_GROUP__EMPLOYER_INTERVIEWS, NOTIF_GROUP__EMPLOYER_MEETINGS, NOTIF_GROUP__EMPLOYER_MESSAGES, NOTIF_GROUP__EMPLOYER_RECRUITER_REQUESTS, NOTIF_GROUP__EMPLOYER_REVIEWS, NOTIF_GROUP__EMPLOYER_STAGE_UPDATES, NOTIF_GROUP__EMPLOYER_TEAM_UPDATES, NOTIF_GROUP__RECRUITER_CANDIDATE_CONNECTIONS, NOTIF_GROUP__RECRUITER_CANDIDATE_UPDATES, NOTIF_GROUP__RECRUITER_INTERVIEWS, NOTIF_GROUP__RECRUITER_JOB_UPDATES, NOTIF_GROUP__RECRUITER_MEETINGS, NOTIF_GROUP__RECRUITER_MESSAGES, NOTIF_GROUP__RECRUITER_REQUESTS_UPDATES, NOTIF_GROUP__RECRUITER_REVIEWS, NOTIF_GROUP__RECRUITER_STAGE_UPDATES } from "./notification-group.js";

export const NOTIF_TYPE__EMPLOYER_RECRUITER_APPLIED: NotificationType = {
    id: 110201,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110200,
    notif_group: NOTIF_GROUP__EMPLOYER_RECRUITER_REQUESTS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_RECRUITER_APPLIED,
    name: 'Recruiter Approval Request',
    title: 'New Recruiter approval request',
    message: 'A recruiter requested to work for your jobs',
};
export const NOTIF_TYPE__EMPLOYER_RECRUITER_WITHDREW: NotificationType = {
    id: 110202,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110200,
    notif_group: NOTIF_GROUP__EMPLOYER_RECRUITER_REQUESTS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_RECRUITER_WITHDREW,
    name: 'Recruiter Withdrawn Request',
    title: 'New Recruiter withdrawn request',
    message: 'A recruiter withdrew their request to work for your jobs',
};
export const NOTIF_TYPE__EMPLOYER_MEMBER_INVITED: NotificationType = {
    id: 110401,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110400,
    notif_group: NOTIF_GROUP__EMPLOYER_TEAM_UPDATES,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MEMBER_INVITED,
    name: 'Team Member Invited',
    title: 'New Team Member Invitation',
    message: 'A new team member has been invited to join your company',
};
export const NOTIF_TYPE__EMPLOYER_MEMBER_JOINED: NotificationType = {
    id: 110402,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110400,
    notif_group: NOTIF_GROUP__EMPLOYER_TEAM_UPDATES,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MEMBER_JOINED,
    name: 'Team Member Joined',
    title: 'New Team Member Joined',
    message: 'A new team member has joined your company',
};
export const NOTIF_TYPE__EMPLOYER_MEMBER_REMOVED: NotificationType = {
    id: 110403,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110400,
    notif_group: NOTIF_GROUP__EMPLOYER_TEAM_UPDATES,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MEMBER_REMOVED,
    name: 'Team Member Removed',
    title: 'Team Member Removed',
    message: 'A team member has been removed from your company',
};
export const NOTIF_TYPE__EMPLOYER_MEMBER_UPDATED: NotificationType = {
    id: 110404,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110400,
    notif_group: NOTIF_GROUP__EMPLOYER_TEAM_UPDATES,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MEMBER_UPDATED,
    name: 'Team Member Updated',
    title: 'Team Member Updated',
    message: 'A team member has been updated in your company',
};

export const NOTIF_TYPE__EMPLOYER_REVIEW_POSTED: NotificationType = {
    id: 110501,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110500,
    notif_group: NOTIF_GROUP__EMPLOYER_REVIEWS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_REVIEW_POSTED,
    name: 'New Review Posted',
    title: 'You have a new review',
    message: 'A new review has been posted for your company',
};

export const NOTIF_TYPE__EMPLOYER_MEETING_CREATED: NotificationType = {
    id: 110711,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110710,
    notif_group: NOTIF_GROUP__EMPLOYER_MEETINGS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MEETING_CREATED,
    name: 'New Meeting Created',
    title: 'You have a new meeting',
    message: 'You have a new meeting scheduled with a recruiter',
};
export const NOTIF_TYPE__EMPLOYER_MEETING_CONFIRMED: NotificationType = {
    id: 110712,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110710,
    notif_group: NOTIF_GROUP__EMPLOYER_MEETINGS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MEETING_CONFIRMED,
    name: 'Meeting Confirmed',
    title: 'Your meeting is confirmed',
    message: 'Your meeting with a recruiter has been confirmed',
};
export const NOTIF_TYPE__EMPLOYER_MEETING_RESCHEDULED: NotificationType = {
    id: 110713,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110710,
    notif_group: NOTIF_GROUP__EMPLOYER_MEETINGS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MEETING_RESCHEDULED,
    name: 'Meeting Rescheduled',
    title: 'Your meeting has been rescheduled',
    message: 'Your meeting with a recruiter has been rescheduled',
};
export const NOTIF_TYPE__EMPLOYER_MEETING_UPDATED: NotificationType = {
    id: 110714,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110710,
    notif_group: NOTIF_GROUP__EMPLOYER_MEETINGS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MEETING_UPDATED,
    name: 'Meeting Updated',
    title: 'Your meeting has been updated',
    message: 'Your meeting with a recruiter has been updated',
};
export const NOTIF_TYPE__EMPLOYER_MEETING_REFUSED: NotificationType = {
    id: 110715,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110710,
    notif_group: NOTIF_GROUP__EMPLOYER_MEETINGS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MEETING_REFUSED,
    name: 'Meeting Refused',
    title: 'Your meeting has been refused',
    message: 'Your meeting with a recruiter has been refused',
};
export const NOTIF_TYPE__EMPLOYER_MEETING_DELETED: NotificationType = {
    id: 110716,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110710,
    notif_group: NOTIF_GROUP__EMPLOYER_MEETINGS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MEETING_DELETED,
    name: 'Meeting Deleted',
    title: 'Your meeting has been deleted',
    message: 'Your meeting with a recruiter has been deleted',
};

export const NOTIF_TYPE__EMPLOYER_MESSAGE_FROM_RECRUITER: NotificationType = {
    id: 110801,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110800,
    notif_group: NOTIF_GROUP__EMPLOYER_MESSAGES,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MESSAGE_FROM_RECRUITER,
    name: 'New Message from Recruiter',
    title: 'You have a new message',
    message: 'You have received a new message from a recruiter',
};
export const NOTIF_TYPE__EMPLOYER_MESSAGE_FROM_CANDIDATE: NotificationType = {
    id: 110802,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 110800,
    notif_group: NOTIF_GROUP__EMPLOYER_MESSAGES,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_MESSAGE_FROM_CANDIDATE,
    name: 'New Message from Candidate',
    title: 'You have a new message',
    message: 'You have received a new message from a candidate',
};

// Hiring Process Notifications
export const NOTIF_TYPE__EMPLOYER_CANDIDATE_PROPOSED: NotificationType = {
    id: 120301,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 120300,
    notif_group: NOTIF_GROUP__EMPLOYER_CANDIDATE_UPDATES,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_CANDIDATE_PROPOSED,
    name: 'New Candidate Proposed by Recruiter',
    title: 'A recruiter has proposed a new candidate',
    message: 'A recruiter has proposed a new candidate for your job',
};

export const NOTIF_TYPE__EMPLOYER_STAGE_CREATED: NotificationType = {
    id: 120201,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 120200,
    notif_group: NOTIF_GROUP__EMPLOYER_STAGE_UPDATES,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_STAGE_CREATED,
    name: 'Hiring Stage Created',
    title: 'A new hiring stage has been created',
    message: 'A new hiring stage has been created in your hiring process',
};
export const NOTIF_TYPE__EMPLOYER_STAGE_UPDATED: NotificationType = {
    id: 120202,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 120200,
    notif_group: NOTIF_GROUP__EMPLOYER_STAGE_UPDATES,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_STAGE_UPDATED,
    name: 'Hiring Stage Updated',
    title: 'A hiring stage has been updated',
    message: 'A hiring stage has been updated in your hiring process',
};
export const NOTIF_TYPE__EMPLOYER_STAGE_DELETED: NotificationType = {
    id: 120203,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 120200,
    notif_group: NOTIF_GROUP__EMPLOYER_STAGE_UPDATES,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_STAGE_DELETED,
    name: 'Hiring Stage Deleted',
    title: 'A hiring stage has been deleted',
    message: 'A hiring stage has been deleted in your hiring process',
};

export const NOTIF_TYPE__EMPLOYER_INTERVIEW_CREATED: NotificationType = {
    id: 120701,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 120700,
    notif_group: NOTIF_GROUP__EMPLOYER_INTERVIEWS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_INTERVIEW_CREATED,
    name: 'New Interview Created',
    title: 'You have a new interview',
    message: 'You have a new interview scheduled with a candidate',
};
export const NOTIF_TYPE__EMPLOYER_INTERVIEW_CONFIRMED: NotificationType = {
    id: 120702,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 120700,
    notif_group: NOTIF_GROUP__EMPLOYER_INTERVIEWS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_INTERVIEW_CONFIRMED,
    name: 'Interview Confirmed',
    title: 'Your interview has been confirmed',
    message: 'Your interview with a candidate has been confirmed',
};
export const NOTIF_TYPE__EMPLOYER_INTERVIEW_RESCHEDULED: NotificationType = {
    id: 120703,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 120700,
    notif_group: NOTIF_GROUP__EMPLOYER_INTERVIEWS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_INTERVIEW_RESCHEDULED,
    name: 'Interview Rescheduled',
    title: 'Your interview has been rescheduled',
    message: 'Your interview with a candidate has been rescheduled',
};
export const NOTIF_TYPE__EMPLOYER_INTERVIEW_UPDATED: NotificationType = {
    id: 120704,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 120700,
    notif_group: NOTIF_GROUP__EMPLOYER_INTERVIEWS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_INTERVIEW_UPDATED,
    name: 'Interview Updated',
    title: 'Your interview has been updated',
    message: 'Your interview with a candidate has been updated',
};
export const NOTIF_TYPE__EMPLOYER_INTERVIEW_REFUSED: NotificationType = {
    id: 120705,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 120700,
    notif_group: NOTIF_GROUP__EMPLOYER_INTERVIEWS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_INTERVIEW_REFUSED,
    name: 'Interview Refused',
    title: 'Your interview has been refused',
    message: 'Your interview with a candidate has been refused',
};
export const NOTIF_TYPE__EMPLOYER_INTERVIEW_DELETED: NotificationType = {
    id: 120706,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 120700,
    notif_group: NOTIF_GROUP__EMPLOYER_INTERVIEWS,
    receiver_profile_id: PROFILE_EMPLOYER.id,
    receiver_profile: PROFILE_EMPLOYER,
    code: NotificationTypeCode.EMPLOYER_INTERVIEW_DELETED,
    name: 'Interview Deleted',
    title: 'Your interview has been deleted',
    message: 'Your interview with a candidate has been deleted',
};

export const NOTIF_TYPE__RECRUITER_JOB_CREATED: NotificationType = {
    id: 210101,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210100,
    notif_group: NOTIF_GROUP__RECRUITER_JOB_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_JOB_CREATED,
    name: 'New Job Created',
    title: 'A new job has been created',
    message: 'A new job has been created by an employer',
};
export const NOTIF_TYPE__RECRUITER_JOB_UPDATED: NotificationType = {
    id: 210102,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210100,
    notif_group: NOTIF_GROUP__RECRUITER_JOB_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_JOB_UPDATED,
    name: 'Job Updated',
    title: 'A job has been updated',
    message: 'A job has been updated by an employer',
};
export const NOTIF_TYPE__RECRUITER_JOB_DELETED: NotificationType = {
    id: 210103,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210100,
    notif_group: NOTIF_GROUP__RECRUITER_JOB_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_JOB_DELETED,
    name: 'Job Deleted',
    title: 'A job has been deleted',
    message: 'A job has been deleted by an employer',
};

export const NOTIF_TYPE__RECRUITER_RECRUITER_APPROVED: NotificationType = {
    id: 210201,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210200,
    notif_group: NOTIF_GROUP__RECRUITER_REQUESTS_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_RECRUITER_APPROVED,
    name: 'Employer Approved You',
    title: 'An employer has approved you',
    message: 'An employer has approved your request to work for their jobs',
};
export const NOTIF_TYPE__RECRUITER_RECRUITER_REJECTED: NotificationType = {
    id: 210202,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210200,
    notif_group: NOTIF_GROUP__RECRUITER_REQUESTS_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_RECRUITER_REJECTED,
    name: 'Employer Rejected You',
    title: 'An employer has rejected you',
    message: 'An employer has rejected your request to work for their jobs',
};
export const NOTIF_TYPE__RECRUITER_RECRUITER_AUTOAPPROVED_ON: NotificationType = {
    id: 210203,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210200,
    notif_group: NOTIF_GROUP__RECRUITER_REQUESTS_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_RECRUITER_AUTOAPPROVED_ON,
    name: 'Employer Autoapproved You',
    title: 'An employer has autoapproved you',
    message: 'An employer has autoapproved your request to work for their jobs',
};
export const NOTIF_TYPE__RECRUITER_RECRUITER_AUTOAPPROVED_OFF: NotificationType = {
    id: 210204,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210200,
    notif_group: NOTIF_GROUP__RECRUITER_REQUESTS_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_RECRUITER_AUTOAPPROVED_OFF,
    name: 'Employer removed Autoapproval',
    title: 'An employer has removed autoapproval',
    message: 'An employer has removed autoapproval for your request to work for their jobs',
};

export const NOTIF_TYPE__RECRUITER_CANDIDATE_CONNECTED: NotificationType = {
    id: 210301,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210300,
    notif_group: NOTIF_GROUP__RECRUITER_CANDIDATE_CONNECTIONS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_CANDIDATE_CONNECTED,
    name: 'New Candidate Connection',
    title: 'A candidate has connected with your company',
    message: 'A candidate has connected with your company',
};
export const NOTIF_TYPE__RECRUITER_CANDIDATE_APPLIED: NotificationType = {
    id: 210302,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210300,
    notif_group: NOTIF_GROUP__RECRUITER_CANDIDATE_CONNECTIONS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_CANDIDATE_APPLIED,
    name: 'New Candidate Application',
    title: 'A candidate has applied to your company',
    message: 'A candidate has applied to your company',
};

export const NOTIF_TYPE__RECRUITER_REVIEW_POSTED: NotificationType = {
    id: 210501,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210500,
    notif_group: NOTIF_GROUP__RECRUITER_REVIEWS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_REVIEW_POSTED,
    name: 'New Review Posted',
    title: 'You have a new review',
    message: 'A new review has been posted for your profile',
};

export const NOTIF_TYPE__RECRUITER_MEETING_CREATED: NotificationType = {
    id: 210711,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210710,
    notif_group: NOTIF_GROUP__RECRUITER_MEETINGS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_MEETING_CREATED,
    name: 'New Meeting Created',
    title: 'You have a new meeting',
    message: 'You have a new meeting scheduled with an employer',
};
export const NOTIF_TYPE__RECRUITER_MEETING_CONFIRMED: NotificationType = {
    id: 210712,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210710,
    notif_group: NOTIF_GROUP__RECRUITER_MEETINGS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_MEETING_CONFIRMED,
    name: 'New Meeting Confirmed',
    title: 'Your meeting is confirmed',
    message: 'Your meeting is confirmed with an employer',
};
export const NOTIF_TYPE__RECRUITER_MEETING_RESCHEDULED: NotificationType = {
    id: 210713,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210710,
    notif_group: NOTIF_GROUP__RECRUITER_MEETINGS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_MEETING_RESCHEDULED,
    name: 'New Meeting Rescheduled',
    title: 'Your meeting is rescheduled',
    message: 'Your meeting is rescheduled with an employer',
};
export const NOTIF_TYPE__RECRUITER_MEETING_UPDATED: NotificationType = {
    id: 210714,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210710,
    notif_group: NOTIF_GROUP__RECRUITER_MEETINGS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_MEETING_UPDATED,
    name: 'New Meeting Updated',
    title: 'Your meeting is updated',
    message: 'Your meeting is updated with an employer',
};
export const NOTIF_TYPE__RECRUITER_MEETING_REFUSED: NotificationType = {
    id: 210715,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210710,
    notif_group: NOTIF_GROUP__RECRUITER_MEETINGS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_MEETING_REFUSED,
    name: 'New Meeting Refused',
    title: 'Your meeting is refused',
    message: 'Your meeting is refused with an employer',
};
export const NOTIF_TYPE__RECRUITER_MEETING_DELETED: NotificationType = {
    id: 210716,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210710,
    notif_group: NOTIF_GROUP__RECRUITER_MEETINGS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_MEETING_DELETED,
    name: 'New Meeting Deleted',
    title: 'Your meeting is deleted',
    message: 'Your meeting is deleted with an employer',
};

export const NOTIF_TYPE__RECRUITER_MESSAGE_FROM_EMPLOYER: NotificationType = {
    id: 210801,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210800,
    notif_group: NOTIF_GROUP__RECRUITER_MESSAGES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_MESSAGE_FROM_EMPLOYER,
    name: 'New Message from Employer',
    title: 'You have a new message',
    message: 'You have received a new message from an employer',
};
export const NOTIF_TYPE__RECRUITER_MESSAGE_FROM_CANDIDATE: NotificationType = {
    id: 210802,
    notif_categ_id: 10,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: 210800,
    notif_group: NOTIF_GROUP__RECRUITER_MESSAGES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_MESSAGE_FROM_CANDIDATE,
    name: 'New Message from Candidate',
    title: 'You have a new message',
    message: 'You have received a new message from a candidate',
};

export const NOTIF_TYPE__RECRUITER_CANDIDATE_STAGE_UPDATED: NotificationType = {
    id: 220301,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220300,
    notif_group: NOTIF_GROUP__RECRUITER_CANDIDATE_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_CANDIDATE_STAGE_UPDATED,
    name: 'Candidate Stage Updated',
    title: 'A candidate stage has been updated',
    message: 'A candidate stage has been updated by an employer',
};
export const NOTIF_TYPE__RECRUITER_CANDIDATE_HIRED: NotificationType = {
    id: 220302,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220300,
    notif_group: NOTIF_GROUP__RECRUITER_CANDIDATE_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_CANDIDATE_HIRED,
    name: 'Candidate Hired',
    title: 'A candidate has been hired',
    message: 'A candidate has been hired by an employer',
};
export const NOTIF_TYPE__RECRUITER_CANDIDATE_REJECTED: NotificationType = {
    id: 220303,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220300,
    notif_group: NOTIF_GROUP__RECRUITER_CANDIDATE_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_CANDIDATE_REJECTED,
    name: 'Candidate Rejected',
    title: 'A candidate has been rejected',
    message: 'A candidate has been rejected by an employer',
};
export const NOTIF_TYPE__RECRUITER_CANDIDATE_TERMINATED: NotificationType = {
    id: 220304,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220300,
    notif_group: NOTIF_GROUP__RECRUITER_CANDIDATE_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_CANDIDATE_TERMINATED,
    name: 'Candidate Terminated',
    title: 'A candidate has been terminated',
    message: 'A candidate has been terminated by an employer',
};

export const NOTIF_TYPE__RECRUITER_INTERVIEW_CREATED: NotificationType = {
    id: 220701,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220700,
    notif_group: NOTIF_GROUP__RECRUITER_INTERVIEWS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_INTERVIEW_CREATED,
    name: 'New Interview Created',
    title: 'You have a new interview',
    message: 'You have a new interview scheduled with a candidate',
};
export const NOTIF_TYPE__RECRUITER_INTERVIEW_CONFIRMED: NotificationType = {
    id: 220702,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220700,
    notif_group: NOTIF_GROUP__RECRUITER_INTERVIEWS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_INTERVIEW_CONFIRMED,
    name: 'New Interview Confirmed',
    title: 'Your interview is confirmed',
    message: 'Your interview is confirmed with a candidate',
};
export const NOTIF_TYPE__RECRUITER_INTERVIEW_RESCHEDULED: NotificationType = {
    id: 220703,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220700,
    notif_group: NOTIF_GROUP__RECRUITER_INTERVIEWS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_INTERVIEW_RESCHEDULED,
    name: 'New Interview Rescheduled',
    title: 'Your interview has been rescheduled',
    message: 'Your interview has been rescheduled with a candidate',
};
export const NOTIF_TYPE__RECRUITER_INTERVIEW_UPDATED: NotificationType = {
    id: 220704,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220700,
    notif_group: NOTIF_GROUP__RECRUITER_INTERVIEWS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_INTERVIEW_UPDATED,
    name: 'New Interview Updated',
    title: 'Your interview has been updated',
    message: 'Your interview has been updated with a candidate',
};
export const NOTIF_TYPE__RECRUITER_INTERVIEW_REFUSED: NotificationType = {
    id: 220705,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220700,
    notif_group: NOTIF_GROUP__RECRUITER_INTERVIEWS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_INTERVIEW_REFUSED,
    name: 'New Interview Refused',
    title: 'Your interview has been refused',
    message: 'Your interview has been refused with a candidate',
};
export const NOTIF_TYPE__RECRUITER_INTERVIEW_DELETED: NotificationType = {
    id: 220706,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220700,
    notif_group: NOTIF_GROUP__RECRUITER_INTERVIEWS,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_INTERVIEW_DELETED,
    name: 'New Interview Deleted',
    title: 'Your interview has been deleted',
    message: 'Your interview has been deleted with a candidate',
};

export const NOTIF_TYPE__RECRUITER_STAGE_CREATED: NotificationType = {
    id: 220201,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220200,
    notif_group: NOTIF_GROUP__RECRUITER_STAGE_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_STAGE_CREATED,
    name: 'Hiring Stage Created',
    title: 'A new hiring stage has been created',
    message: 'A new hiring stage has been created in your hiring process',
};
export const NOTIF_TYPE__RECRUITER_STAGE_UPDATED: NotificationType = {
    id: 220202,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220200,
    notif_group: NOTIF_GROUP__RECRUITER_STAGE_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_STAGE_UPDATED,
    name: 'Hiring Stage Updated',
    title: 'A hiring stage has been updated',
    message: 'A hiring stage has been updated in your hiring process',
};
export const NOTIF_TYPE__RECRUITER_STAGE_DELETED: NotificationType = {
    id: 220203,
    notif_categ_id: 20,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: 220200,
    notif_group: NOTIF_GROUP__RECRUITER_STAGE_UPDATES,
    receiver_profile_id: PROFILE_RECRUITER.id,
    receiver_profile: PROFILE_RECRUITER,
    code: NotificationTypeCode.RECRUITER_STAGE_DELETED,
    name: 'Hiring Stage Deleted',
    title: 'A hiring stage has been deleted',
    message: 'A hiring stage has been deleted in your hiring process',
};

export const NOTIF_TYPE__CANDIDATE_REVIEW_POSTED: NotificationType = {
    id: 310501,
    notif_categ_id: NOTIF_CATEG__GENERAL.id,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: NOTIF_GROUP__CANDIDATE_REVIEWS.id,
    notif_group: NOTIF_GROUP__CANDIDATE_REVIEWS,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_REVIEW_POSTED,
    name: 'New Review Posted',
    title: 'You have a new review',
    message: 'A new review has been posted for your profile',
};

export const NOTIF_TYPE__CANDIDATE_MESSAGE_FROM_EMPLOYER: NotificationType = {
    id: 310801,
    notif_categ_id: NOTIF_CATEG__GENERAL.id,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: NOTIF_GROUP__CANDIDATE_MESSAGES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_MESSAGES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_MESSAGE_FROM_EMPLOYER,
    name: 'New Message from Employer',
    title: 'You have a new message',
    message: 'An employer has sent you a new message',
};
export const NOTIF_TYPE__CANDIDATE_MESSAGE_FROM_RECRUITER: NotificationType = {
    id: 310802,
    notif_categ_id: NOTIF_CATEG__GENERAL.id,
    notif_categ: NOTIF_CATEG__GENERAL,
    notif_group_id: NOTIF_GROUP__CANDIDATE_MESSAGES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_MESSAGES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_MESSAGE_FROM_RECRUITER,
    name: 'New Message from Recruiter',
    title: 'You have a new message',
    message: 'A recruiter has sent you a new message',
};

export const NOTIF_TYPE__CANDIDATE_STAGE_CREATED: NotificationType = {
    id: 320201,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_STAGE_UPDATES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_STAGE_UPDATES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_STAGE_CREATED,
    name: 'Hiring Stage Created',
    title: 'A hiring stage has been created',
    message: 'A hiring stage has been created in your hiring process',
};
export const NOTIF_TYPE__CANDIDATE_STAGE_UPDATED: NotificationType = {
    id: 320202,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_STAGE_UPDATES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_STAGE_UPDATES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_STAGE_UPDATED,
    name: 'Hiring Stage Updated',
    title: 'A hiring stage has been updated',
    message: 'A hiring stage has been updated in your hiring process',
};
export const NOTIF_TYPE__CANDIDATE_STAGE_DELETED: NotificationType = {
    id: 320203,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_STAGE_UPDATES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_STAGE_UPDATES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_STAGE_DELETED,
    name: 'Hiring Stage Deleted',
    title: 'A hiring stage has been deleted',
    message: 'A hiring stage has been deleted in your hiring process',
};
export const NOTIF_TYPE__CANDIDATE_PROPOSED: NotificationType = {
    id: 320301,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_PROPOSED,
    name: 'New Candidate Proposed',
    title: 'You have been proposed to a job',
    message: 'You have been proposed to a job by a recruiter',
};
export const NOTIF_TYPE__CANDIDATE_STATUS_UPDATED: NotificationType = {
    id: 320302,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_STATUS_UPDATED,
    name: 'Hiring Stage Updated',
    title: 'A hiring stage has been updated',
    message: 'You have been transitioned to a new stage in your application',
};
export const NOTIF_TYPE__CANDIDATE_HIRED: NotificationType = {
    id: 320303,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_HIRED,
    name: 'Candidate Hired',
    title: 'You have been hired',
    message: 'You have been hired for a job',
};
export const NOTIF_TYPE__CANDIDATE_REJECTED: NotificationType = {
    id: 320304,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_REJECTED,
    name: 'Candidate Rejected',
    title: 'You have been rejected',
    message: 'You have been rejected for a job',
};
export const NOTIF_TYPE__CANDIDATE_TERMINATED: NotificationType = {
    id: 320305,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_TERMINATED,
    name: 'Candidate Terminated',
    title: 'You have been terminated',
    message: 'You have been terminated from a job',
};
export const NOTIF_TYPE__CANDIDATE_SHORTLISTED: NotificationType = {
    id: 320308,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES.id,
    notif_group: NOTIF_GROUP__CANDIDATE_STATUS_UPDATES,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_SHORTLISTED,
    name: 'Candidate Shortlisted',
    title: 'You have been shortlisted',
    message: 'You have been shortlisted for a job',
};
export const NOTIF_TYPE__CANDIDATE_INTERVIEW_CREATED: NotificationType = {
    id: 320701,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_INTERVIEWS.id,
    notif_group: NOTIF_GROUP__CANDIDATE_INTERVIEWS,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_INTERVIEW_CREATED,
    name: 'New Interview Created',
    title: 'A new interview has been created',
    message: 'A new interview has been scheduled for you',
};
export const NOTIF_TYPE__CANDIDATE_INTERVIEW_CONFIRMED: NotificationType = {
    id: 320702,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_INTERVIEWS.id,
    notif_group: NOTIF_GROUP__CANDIDATE_INTERVIEWS,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_INTERVIEW_CONFIRMED,
    name: 'Interview Confirmed',
    title: 'An interview has been confirmed',
    message: 'Your interview has been confirmed',
};
export const NOTIF_TYPE__CANDIDATE_INTERVIEW_RESCHEDULED: NotificationType = {
    id: 320703,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_INTERVIEWS.id,
    notif_group: NOTIF_GROUP__CANDIDATE_INTERVIEWS,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_INTERVIEW_RESCHEDULED,
    name: 'Interview Rescheduled',
    title: 'An interview has been rescheduled',
    message: 'Your interview has been rescheduled',
};
export const NOTIF_TYPE__CANDIDATE_INTERVIEW_UPDATED: NotificationType = {
    id: 320704,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_INTERVIEWS.id,
    notif_group: NOTIF_GROUP__CANDIDATE_INTERVIEWS,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_INTERVIEW_UPDATED,
    name: 'Interview Updated',
    title: 'An interview has been updated',
    message: 'Your interview has been updated',
};
export const NOTIF_TYPE__CANDIDATE_INTERVIEW_REFUSED: NotificationType = {
    id: 320705,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_INTERVIEWS.id,
    notif_group: NOTIF_GROUP__CANDIDATE_INTERVIEWS,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_INTERVIEW_REFUSED,
    name: 'Interview Refused',
    title: 'An interview has been refused',
    message: 'Your interview has been refused',
};
export const NOTIF_TYPE__CANDIDATE_INTERVIEW_DELETED: NotificationType = {
    id: 320706,
    notif_categ_id: NOTIF_CATEG__HIRING_PROCESS.id,
    notif_categ: NOTIF_CATEG__HIRING_PROCESS,
    notif_group_id: NOTIF_GROUP__CANDIDATE_INTERVIEWS.id,
    notif_group: NOTIF_GROUP__CANDIDATE_INTERVIEWS,
    receiver_profile_id: PROFILE_CANDIDATE.id,
    receiver_profile: PROFILE_CANDIDATE,
    code: NotificationTypeCode.CANDIDATE_INTERVIEW_DELETED,
    name: 'Interview Deleted',
    title: 'An interview has been deleted',
    message: 'Your interview has been deleted',
};

export const NOTIF_TYPES: NotificationType[] = [
    NOTIF_TYPE__EMPLOYER_RECRUITER_APPLIED,
    NOTIF_TYPE__EMPLOYER_RECRUITER_WITHDREW,
    NOTIF_TYPE__EMPLOYER_MEMBER_INVITED,
    NOTIF_TYPE__EMPLOYER_MEMBER_JOINED,
    NOTIF_TYPE__EMPLOYER_MEMBER_REMOVED,
    NOTIF_TYPE__EMPLOYER_MEMBER_UPDATED,
    NOTIF_TYPE__EMPLOYER_REVIEW_POSTED,
    NOTIF_TYPE__EMPLOYER_MEETING_CREATED,
    NOTIF_TYPE__EMPLOYER_MEETING_CONFIRMED,
    NOTIF_TYPE__EMPLOYER_MEETING_RESCHEDULED,
    NOTIF_TYPE__EMPLOYER_MEETING_UPDATED,
    NOTIF_TYPE__EMPLOYER_MEETING_REFUSED,
    NOTIF_TYPE__EMPLOYER_MEETING_DELETED,
    NOTIF_TYPE__EMPLOYER_MESSAGE_FROM_RECRUITER,
    NOTIF_TYPE__EMPLOYER_MESSAGE_FROM_CANDIDATE,
    NOTIF_TYPE__EMPLOYER_STAGE_CREATED,
    NOTIF_TYPE__EMPLOYER_STAGE_UPDATED,
    NOTIF_TYPE__EMPLOYER_STAGE_DELETED,
    NOTIF_TYPE__EMPLOYER_CANDIDATE_PROPOSED,
    NOTIF_TYPE__EMPLOYER_INTERVIEW_CREATED,
    NOTIF_TYPE__EMPLOYER_INTERVIEW_CONFIRMED,
    NOTIF_TYPE__EMPLOYER_INTERVIEW_RESCHEDULED,
    NOTIF_TYPE__EMPLOYER_INTERVIEW_UPDATED,
    NOTIF_TYPE__EMPLOYER_INTERVIEW_REFUSED,
    NOTIF_TYPE__EMPLOYER_INTERVIEW_DELETED,

    NOTIF_TYPE__RECRUITER_JOB_CREATED,
    NOTIF_TYPE__RECRUITER_JOB_UPDATED,
    NOTIF_TYPE__RECRUITER_JOB_DELETED,
    NOTIF_TYPE__RECRUITER_RECRUITER_APPROVED,
    NOTIF_TYPE__RECRUITER_RECRUITER_REJECTED,
    NOTIF_TYPE__RECRUITER_RECRUITER_AUTOAPPROVED_ON,
    NOTIF_TYPE__RECRUITER_RECRUITER_AUTOAPPROVED_OFF,
    NOTIF_TYPE__RECRUITER_CANDIDATE_CONNECTED,
    NOTIF_TYPE__RECRUITER_CANDIDATE_APPLIED,
    NOTIF_TYPE__RECRUITER_REVIEW_POSTED,
    NOTIF_TYPE__RECRUITER_MEETING_CREATED,
    NOTIF_TYPE__RECRUITER_MEETING_CONFIRMED,
    NOTIF_TYPE__RECRUITER_MEETING_RESCHEDULED,
    NOTIF_TYPE__RECRUITER_MEETING_UPDATED,
    NOTIF_TYPE__RECRUITER_MEETING_REFUSED,
    NOTIF_TYPE__RECRUITER_MEETING_DELETED,
    NOTIF_TYPE__RECRUITER_MESSAGE_FROM_EMPLOYER,
    NOTIF_TYPE__RECRUITER_MESSAGE_FROM_CANDIDATE,
    NOTIF_TYPE__RECRUITER_STAGE_CREATED,
    NOTIF_TYPE__RECRUITER_STAGE_UPDATED,
    NOTIF_TYPE__RECRUITER_STAGE_DELETED,
    NOTIF_TYPE__RECRUITER_CANDIDATE_STAGE_UPDATED,
    NOTIF_TYPE__RECRUITER_CANDIDATE_HIRED,
    NOTIF_TYPE__RECRUITER_CANDIDATE_REJECTED,
    NOTIF_TYPE__RECRUITER_CANDIDATE_TERMINATED,
    NOTIF_TYPE__RECRUITER_INTERVIEW_CREATED,
    NOTIF_TYPE__RECRUITER_INTERVIEW_CONFIRMED,
    NOTIF_TYPE__RECRUITER_INTERVIEW_RESCHEDULED,
    NOTIF_TYPE__RECRUITER_INTERVIEW_UPDATED,
    NOTIF_TYPE__RECRUITER_INTERVIEW_REFUSED,
    NOTIF_TYPE__RECRUITER_INTERVIEW_DELETED,

    NOTIF_TYPE__CANDIDATE_REVIEW_POSTED,
    NOTIF_TYPE__CANDIDATE_MESSAGE_FROM_EMPLOYER,
    NOTIF_TYPE__CANDIDATE_MESSAGE_FROM_RECRUITER,
    NOTIF_TYPE__CANDIDATE_STAGE_CREATED,
    NOTIF_TYPE__CANDIDATE_STAGE_UPDATED,
    NOTIF_TYPE__CANDIDATE_STAGE_DELETED,
    NOTIF_TYPE__CANDIDATE_PROPOSED,
    NOTIF_TYPE__CANDIDATE_STATUS_UPDATED,
    NOTIF_TYPE__CANDIDATE_HIRED,
    NOTIF_TYPE__CANDIDATE_REJECTED,
    NOTIF_TYPE__CANDIDATE_TERMINATED,
    NOTIF_TYPE__CANDIDATE_SHORTLISTED,
    NOTIF_TYPE__CANDIDATE_INTERVIEW_CREATED,
    NOTIF_TYPE__CANDIDATE_INTERVIEW_CONFIRMED,
    NOTIF_TYPE__CANDIDATE_INTERVIEW_RESCHEDULED,
    NOTIF_TYPE__CANDIDATE_INTERVIEW_UPDATED,
    NOTIF_TYPE__CANDIDATE_INTERVIEW_REFUSED,
    NOTIF_TYPE__CANDIDATE_INTERVIEW_DELETED,
];