export enum ProfileCode {
    ADMIN = 'ADMIN',
    EMPLOYER = 'EMPLOYER',
    RECRUITER = 'RECRUITER',
    CANDIDATE = 'CANDIDATE',
}

export enum RoleCode {
    PLATFORM_ADMIN = 'PLATFORM_ADMIN',
    ADMINISTRATOR = 'ADMINISTRATOR',
    HIRING_TEAM = 'HIRING_TEAM',
    INTERNAL_RECRUITER = 'INTERNAL_RECRUITER',
    NO_ACCESS = 'NO_ACCESS',
    RECRUITER = 'RECRUITER',
    CANDIDATE = 'CANDIDATE',
}

export enum RightCode {
    JOB__LIST__VIEW = 'JOB__LIST__VIEW',
    JOB__ITEM__VIEW = 'JOB__ITEM__VIEW',
    JOB__ITEM__CREATE = 'JOB__ITEM__CREATE',
    JOB__ITEM__EDIT = 'JOB__ITEM__EDIT',
    JOB__ITEM__DELETE = 'JOB__ITEM__DELETE',
    JOB__FAVORITE__EDIT = 'JOB__FAVORITE__EDIT',
    JOB__KANBAN__VIEW = 'JOB__KANBAN__VIEW',
    JOB_APPLICATION__LIST__VIEW = 'JOB_APPLICATION__LIST__VIEW',
    JOB_APPLICATION__ITEM__REQUEST = 'JOB_APPLICATION__ITEM__REQUEST',
    JOB_APPLICATION__ITEM__APPROVE = 'JOB_APPLICATION__ITEM__APPROVE',
    JOB_APPLICATION__ITEM__AUTOAPPROVE = 'JOB_APPLICATION__ITEM__AUTOAPPROVE',
    JOB_APPLICATION__ITEM__REJECT = 'JOB_APPLICATION__ITEM__REJECT',
    JOB_APPLICATION__ITEM__WITHDRAW = 'JOB_APPLICATION__ITEM__WITHDRAW',
    JOB_APPLICATION__RECRUITER_LIST__VIEW = 'JOB_APPLICATION__RECRUITER_LIST__VIEW',
    JOB_APPLICATION__CANDIDATE_LIST__VIEW = 'JOB_APPLICATION__CANDIDATE_LIST__VIEW',
    JOB_APPLICATION__CANDIDATE__ADD = 'JOB_APPLICATION__CANDIDATE__ADD',
    JOB_APPLICATION__CANDIDATE__EDIT = 'JOB_APPLICATION__CANDIDATE__EDIT',
    JOB_APPLICATION__CANDIDATE__DELETE = 'JOB_APPLICATION__CANDIDATE__DELETE',
    STAGE__LIST__VIEW = 'STAGE__LIST__VIEW',
    STAGE__ITEM__CREATE = 'STAGE__ITEM__CREATE',
    STAGE__ITEM__EDIT = 'STAGE__ITEM__EDIT',
    STAGE__ITEM__DELETE = 'STAGE__ITEM__DELETE',
    JOB_HIRES__LIST__VIEW = 'JOB_HIRES__LIST__VIEW',
    JOB_HIRES__ITEM__VIEW = 'JOB_HIRES__ITEM__VIEW',
    JOB_HIRES__ITEM__CREATE = 'JOB_HIRES__ITEM__CREATE',
    JOB_HIRES__ITEM__DELETE = 'JOB_HIRES__ITEM__DELETE',
    EVENT__LIST__VIEW = 'EVENT__LIST__VIEW',
    EVENT__ITEM__VIEW = 'EVENT__ITEM__VIEW',
    EVENT__ITEM__CREATE = 'EVENT__ITEM__CREATE',
    EVENT__ITEM__EDIT__OWN = 'EVENT__ITEM__EDIT__OWN',
    EVENT__ITEM__EDIT__TARGET = 'EVENT__ITEM__EDIT__TARGET',
    EVENT__ITEM__EDIT__OTHER = 'EVENT__ITEM__EDIT__OTHER',
    EVENT__ITEM__CONFIRM__OWN = 'EVENT__ITEM__CONFIRM__OWN',
    EVENT__ITEM__CONFIRM__TARGET = 'EVENT__ITEM__CONFIRM__TARGET',
    EVENT__ITEM__CONFIRM__OTHER = 'EVENT__ITEM__CONFIRM__OTHER',
    EVENT__ITEM__RESCHEDULE__OWN = 'EVENT__ITEM__RESCHEDULE__OWN',
    EVENT__ITEM__RESCHEDULE__TARGET = 'EVENT__ITEM__RESCHEDULE__TARGET',
    EVENT__ITEM__RESCHEDULE__OTHER = 'EVENT__ITEM__RESCHEDULE__OTHER',
    EVENT__ITEM__REFUSE__OWN = 'EVENT__ITEM__REFUSE__OWN',
    EVENT__ITEM__REFUSE__TARGET = 'EVENT__ITEM__REFUSE__TARGET',
    EVENT__ITEM__REFUSE__OTHER = 'EVENT__ITEM__REFUSE__OTHER',
    EVENT__ITEM__DELETE__OWN = 'EVENT__ITEM__DELETE__OWN',
    EVENT__ITEM__DELETE__TARGET = 'EVENT__ITEM__DELETE__TARGET',
    EVENT__ITEM__DELETE__OTHER = 'EVENT__ITEM__DELETE__OTHER',
    MESSAGE__LIST__VIEW = 'MESSAGE__LIST__VIEW',
    MESSAGE__ITEM__CREATE = 'MESSAGE__ITEM__CREATE',
    REVIEW__LIST__VIEW = 'REVIEW__LIST__VIEW',
    REVIEW__ITEM__CREATE = 'REVIEW__ITEM__CREATE',
    TODO__LIST__VIEW = 'TODO__LIST__VIEW',
    TODO__ITEM__CREATE = 'TODO__ITEM__CREATE',
    TODO__ITEM__EDIT = 'TODO__ITEM__EDIT',
    TODO__ITEM__DELETE = 'TODO__ITEM__DELETE',
    USER__LIST__VIEW = 'USER__LIST__VIEW',
    USER__ITEM__VIEW = 'USER__ITEM__VIEW',
    USER__ITEM__CREATE = 'USER__ITEM__CREATE',
    USER__ITEM__DELETE = 'USER__ITEM__DELETE',
    USER__PROFILE__VIEW = 'USER__PROFILE__VIEW',
    USER__PROFILE__EDIT = 'USER__PROFILE__EDIT',
    USER__SETTINGS__VIEW = 'USER__SETTINGS__VIEW',
    USER__SETTINGS__EDIT = 'USER__SETTINGS__EDIT',
    EMPLOYER__LIST__VIEW = 'EMPLOYER__LIST__VIEW',
    EMPLOYER__ITEM__VIEW = 'EMPLOYER__ITEM__VIEW',
    EMPLOYER__TEAM_LIST__VIEW = 'EMPLOYER__TEAM_LIST__VIEW',
    EMPLOYER__TEAM_MEMBER__DELETE = 'EMPLOYER__TEAM_MEMBER__DELETE',
    EMPLOYER__INVITE__CREATE = 'EMPLOYER__INVITE__CREATE',
    EMPLOYER__INVITE__DELETE = 'EMPLOYER__INVITE__DELETE',
    RECRUITER__LIST__VIEW = 'RECRUITER__LIST__VIEW',
    RECRUITER__ITEM__VIEW = 'RECRUITER__ITEM__VIEW',
    CANDIDATE__LIST__VIEW = 'CANDIDATE__LIST__VIEW',
    CANDIDATE__ITEM__VIEW = 'CANDIDATE__ITEM__VIEW',
    CANDIDATE__INVITE__CREATE = 'CANDIDATE__INVITE__CREATE',
    CANDIDATE__IDEAL_JOB__CREATE = 'CANDIDATE__IDEAL_JOB__CREATE',
    CANDIDATE__IDEAL_JOB__EDIT = 'CANDIDATE__IDEAL_JOB__EDIT',
    COMPANY__ITEM__VIEW = 'COMPANY__ITEM__VIEW',
    COMPANY__ITEM__EDIT = 'COMPANY__ITEM__EDIT',
    ADMIN__USER_LIST__VIEW = 'ADMIN__USER_LIST__VIEW',
    ADMIN__USER__ACTIVATE = 'ADMIN__USER__ACTIVATE',
    ADMIN__COMPANY_ACTIVATE = 'ADMIN__COMPANY_ACTIVATE'
}

export enum JobTypeCode {
    FULL_TIME = 'FULL_TIME',
    PART_TIME = 'PART_TIME',
    CONTRACT = 'CONTRACT',
}

export enum PresenceStatusCode {
    ONSITE = 'ONSITE',
    REMOTE = 'REMOTE',
    HYBRID = 'HYBRID',
}

export enum UrgencyCode {
    REGULAR = 'REGULAR',
    URGENT = 'URGENT',
}

export enum TagTypeCode {
    TAG = 'TAG',
    SKILL = 'SKILL',
}

export enum SkillTypeCode {
    TECHNICAL = 'TECHNICAL',
    OTHER = 'OTHER',
    BONUS = 'BONUS',
}

export enum JobApplicationStatusCode {
    AUTOAPPROVED = 'AUTOAPPROVED',
    APPROVED = 'APPROVED',
    PENDING = 'PENDING',
    REJECTED = 'REJECTED',
    WITHDRAWN = 'WITHDRAWN',
}

export enum StageTypeName {
    SCREENING = 'Screening',
    INTERVIEW = 'Interview',
    OFFER = 'Offer',
}

export enum StageCategoryName {
    MANDATORY = 'Mandatory',
    DEFAULT = 'Default',
    CUSTOM = 'Custom',
}

export enum StageOwnerTypeName {
    EMPLOYER = 'Employer',
    RECRUITER = 'Recruiter',
}

export enum CalendarEventStatusName {
    PENDING = 'Pending',
    CONFIRMED = 'Confirmed',
    REFUSED = 'Refused',
}

export enum CalendarEventTypeName {
    INTERVIEW = 'Interview',
    MEETING = 'Meeting',
}